# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gmath3D 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gmath3D"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Toshiyasu Shimizu"]
  s.date = "2015-03-17"
  s.description = "This library defines 3D geometric elements(point, line, plane etc..). It can get two(or more) elements relation, like distance between two elements."
  s.email = "toshi0328@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "gmath3D.gemspec",
    "lib/box.rb",
    "lib/ellipse.rb",
    "lib/ext.rb",
    "lib/finite_line.rb",
    "lib/geom.rb",
    "lib/gmath3D.rb",
    "lib/line.rb",
    "lib/plane.rb",
    "lib/polyline.rb",
    "lib/quat.rb",
    "lib/rectangle.rb",
    "lib/tri_mesh.rb",
    "lib/triangle.rb",
    "lib/util.rb",
    "lib/vector3.rb",
    "test/helper.rb",
    "test/test_box.rb",
    "test/test_ellipse.rb",
    "test/test_finite_line.rb",
    "test/test_geom.rb",
    "test/test_line.rb",
    "test/test_matrix_util.rb",
    "test/test_plane.rb",
    "test/test_polyline.rb",
    "test/test_quat.rb",
    "test/test_rectangle.rb",
    "test/test_tri_mesh.rb",
    "test/test_triangle.rb",
    "test/test_util.rb",
    "test/test_vector3.rb"
  ]
  s.homepage = "http://github.com/toshi0328/gmath3D"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Geometric elements in 3D"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<minitest>, ["~> 5.5"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<minitest>, ["~> 5.5"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<minitest>, ["~> 5.5"])
  end
end

